### PR TITLE
Enhancement/authentication support

### PR DESCRIPTION
**Pull request by rpcope1**
I know this is a pretty significant PR, but this adds support for both user auth (via HTTP basic auth) and API Key auth to our API, as well as allowing user creation and login via the API, and API key management (create, read, and delete). There is a lot to unpack here, so please ask questions as you see confusing things.

### CODE REVIEW

**Comment by jjniemeyer** [comment]
Did you remove Travis CI? If so, do you want me to provision the add-on for heroku CI?

**Comment by rpcope1** [comment]
> @rpcope1 Did you remove Travis CI? If so, do you want me to provision the add-on for heroku CI?

Not intentionally, looks like it is still building.

**Comment by rpcope1** [comment]
> Wow, there is lot here! Where did you learn all this?
> 
> I'm approving this change because it contains a lot of things we need and it doesn't break the build.
> 
> However, this _**did**_ break my test db page, but only temporarily. This problem occurs because when heroku deploys a test build it is given a "new" app name, (wifiology-PR-##). Whereas our production app is always called Wifiology and that is the app for which our DB is provisioned.
> 
> A cludgey work around for this is to run the DDL for each testing app. --this could get ugly
> 
> A better solution is probably to replicate to DB locally using `heroku pg:pull` and then run local builds before submitting PR's

This is similar to what I do at work, so bolting a lot of this in isn't a big deal. Again, I can explain any and all of this as people have questions. 

As far as the Heroku build, I want to make sure I understand: the application for the PR fails to deploy because the schema hasn't been run on the new DB for the PR application, or something else?

**Comment by jjniemeyer** [comment]
> > Wow, there is lot here! Where did you learn all this?
> > I'm approving this change because it contains a lot of things we need and it doesn't break the build.
> > However, this _**did**_ break my test db page, but only temporarily. This problem occurs because when heroku deploys a test build it is given a "new" app name, (wifiology-PR-##). Whereas our production app is always called Wifiology and that is the app for which our DB is provisioned.
> > A cludgey work around for this is to run the DDL for each testing app. --this could get ugly
> > A better solution is probably to replicate to DB locally using `heroku pg:pull` and then run local builds before submitting PR's
> 
> This is similar to what I do at work, so bolting a lot of this in isn't a big deal. Again, I can explain any and all of this as people have questions.
> 
> As far as the Heroku build, I want to make sure I understand: the application for the PR fails to deploy because the schema hasn't been run on the new DB for the PR application, or something else?

The build is fine, in that it _does_ build.  

The schema has not been run on _this instance_ of the deployment. Schema has been run on everything that actually gets deployed to "wifiology.herokuapp.com"  . These test builds, all have a different name "wifiology-PR-xx" ....Heroku treats each of these as a seperate app. So we can copy the db to every test app just to be sure, or we keep local copies of the DB for testing.

**Comment by jjniemeyer** [comment]
Also, I already tested this one by deploying it to production temporarily, so its definitely fine to merge

**Comment by jjniemeyer** [comment]
`<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/uQ1ECuzwyadSE" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/satisfying-cookie-squish-uQ1ECuzwyadSE">via GIPHY</a></p>`

**Comment by jjniemeyer** [comment]
merge squish

**Pull request merged**
